version: "3"

vars:
  GREETING: Hello, Space Developer!

tasks:
    default:
        cmds:
        - echo "{{.GREETING}}"
        silent: true

    build-tools:
        desc: Build the software tools
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/spacesvr cmd/server/main.go 
        - chmod 755 bin/spacesvr
        - cp bin/spacesvr $GOPATH/bin
        - GOFLAGS=-mod=mod go build -o bin/spacectl cmd/client/main.go 
        - chmod 755 bin/spacectl
        - cp bin/spacectl $GOPATH/bin

    build-web:
        desc: Build the web application
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/spacectl cmd/client/main.go 
        - GOFLAGS=-mod=mod go build -o bin/spacesvr cmd/server/main.go 

    build-desktop-darwin:
        desc: Build the desktop application for current OS
        cmds:
        - guiutl package -name "Bhojpur Space" -os darwin -sourceDir internal/view/main.go -icon internal/Icon.png

    build-desktop-linux:
        desc: Build the desktop application for current OS
        cmds:
        - guiutl package -name "Bhojpur Space" -os linux -sourceDir internal/view/main.go -icon internal/Icon.png

    build-desktop-windows:
        desc: Build the desktop application for current OS
        cmds:
        - guiutl package -name "Bhojpur Space" -os windows -sourceDir internal/view/main.go -icon internal/Icon.png

    package-android:
        desc: Package the mobile application for Android
        cmds:
        - guiutl package -name "Bhojpur Space" -os android -appID net.bhojpur.space -icon internal/Icon.png

    package-ios:
        desc: Package the mobile application for iOS
        cmds:
        - guiutl package -name "Bhojpur Space" -os ios -appID net.bhojpur.space -icon internal/Icon.png

    release-macos:
        desc: Release the native application for macOS App Store
        cmds:
        - guiutl release -appID net.bhojpur.space -appVersion 1.0 -appBuild 1 -category business

    release-android:
        desc: Release the mobile application for Google Play
        cmds:
        - guiutl release -os android -appID net.bhojpur.space -appVersion 1.0 -appBuild 1

    release-ios:
        desc: Release the mobile application for iOS App Store
        cmds:
        - guiutl release -os ios -appID net.bhojpur.space -appVersion 1.0 -appBuild 1

    run-web-client:
        desc: Run the web client application from source code
        cmds:
        - GOFLAGS=-mod=mod go run cmd/client/main.go
 
    run-web-server:
        desc: Run the web server application from source code
        cmds:
        - GOFLAGS=-mod=mod go run cmd/server/main.go

    run-mobile:
        desc: Run the mobile client application on emulator
        cmds:
        - GOFLAGS=-mod=mod go run -tags mobile internal/view/main.go

    run-desktop: 
        desc: Run the desktop application on local host
        cmds:
        - GOFLAGS=-mod=mod go run internal/view/main.go

    generate:
        desc: Generate Go source code from Protool Buffers
        cmds:
        - protoc --go_out=plugins=grpc:. --go_opt=paths=source_relative pkg/api/v1/space.proto
        - protoc --go_out=plugins=grpc:. --go_opt=paths=source_relative pkg/api/v1/space-ui.proto
        - GOFLAGS=-mod=mod go generate ./...

    test:
        desc: Execute all the Unit Tests
        cmds:
        - gotestsum --junitfile test-results/unit-tests.xml -- -short -race -cover -coverprofile test-results/cover.out ./...

    swagger.gen:
        desc: Generate Go code
        cmds:
        - GOFLAGS=-mod=mod go generate bhojpur.net/space/internal bhojpur.net/space/pkg/swagger

    swagger.validate:
        desc: Validate all the Swagger API specifications
        cmds:
        - swagger validate pkg/swagger/swagger.yml

    swagger.doc:
        desc: Generate documentation for Swagger specified APIs
        cmds:
        - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html